### ISSUE TITLE
Receiving error in console that form isn't connected

### ISSUE THREAD

**Issue by mserr113** [mserr113/Web-Developer-P6#1]
@AccessiT3ch  Can't figure out what I am doing wrong on line 17 of my app.js - added a comment in line here: [https://github.com/mserr113/Web-Developer-P6/commit/1f179ffab5fc4f2af0c49341b1d3bd93f540b4c0#r93369147](url)

**Comment by AccessiT3ch** [comment]
@mserr113 can you send a screenshot of the error?

**Comment by AccessiT3ch** [comment]
<img width="602" alt="Screenshot 2022-12-16 at 5 46 01 PM" src="https://user-images.githubusercontent.com/95449364/208217530-6e29a4ca-f961-4c7c-aee9-2473b62c9837.png">

It looks like there's some thing going on in the front end.

**Comment by mserr113** [comment]
Ok, thanks. I'll take a look at the frontend to try to figure it out. Assumed I wouldn't have to touch the frontend, and it was caused by something I did on the backend.

**Comment by AccessiT3ch** [comment]
Seems to be coming from here somewhere, but not sure why: https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/auth/signup/signup.component.ts#L33-L44

Which is using this function: https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/services/auth.service.ts#L19

**Comment by AccessiT3ch** [comment]
> Seems to be coming from here somewhere, but not sure why: https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/auth/signup/signup.component.ts#L33-L44

Which is using this function: https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/services/auth.service.ts#L19

@mserr113 I would try and console.log the username and password at different points to make sure things aren't null or undefined for some reason!

**Comment by mserr113** [comment]
Added the console log in 3 places to see if it turned up null at all. It only appeared once, but wasn't null in any instance. 
![email and pw](https://user-images.githubusercontent.com/104605862/208219444-27ef9489-4b91-4848-a350-f091dcce95e1.png)
![terminal console log](https://user-images.githubusercontent.com/104605862/208219454-dddf45bb-c0aa-4cb9-83cb-e1997a33fd9e.png)
![email and pw](https://user-images.githubusercontent.com/104605862/208219462-7d7d3138-dd1d-4193-a8c6-4a05cfbd1bea.png)

**Comment by AccessiT3ch** [comment]
@mserr113 - I think I figured out what's going on!

After the user signs up, the auth [component (in the frontend) tries to log the user](https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/auth/signup/signup.component.ts#L33-L34) in by making a second API request. It is this [second API request which is expecting data](https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/services/auth.service.ts#L32) from the server [and not getting any](https://github.com/mserr113/Web-Developer-P6/blob/master/back/controllers/user.js#L8).

At this point, you don't have data being returned by either route, and the cryptic error is getting [swallowed up by the frontend](https://github.com/mserr113/Web-Developer-P6/blob/master/src/app/auth/signup/signup.component.ts#LL39-L43). Adding the line `throw new Error(error.message);` to the `.catch` callback still results in a pretty cryptic error, but at least it includes a stack trace!
