### ISSUE TITLE
Are these routes already created? 

### ISSUE THREAD

**Issue by mserr113** [mserr113/Web-Developer-P6#2]
# @AccessiT3ch  I started to create routes in the app.js file, but the routes I created are looking very similar to code in the 'src folder, eg. this onSubmit code that is in the sauce-form.component.ts file looks it may be updating the api when a sauce form is submitted. Should I not be creating a post route to add sauces to the api when the sauce form is submitted? 

![Screenshot_20221227_033220](https://user-images.githubusercontent.com/104605862/209719686-97d183bd-fddd-4ca2-a99c-4a81c3a2ee2a.png)

**Comment by AccessiT3ch** [comment]
@mserr113 It looks like there is a [`put` route]( https://github.com/mserr113/Web-Developer-P6/blob/master/back/app.js#L76) where MingoDB is updating existing sauces, can you tell if the controller is being triggered when submitting the form?
